// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7BZmAShikeyMkT-fewh76ekp_JMBLibY',
    appId: '1:262292692678:web:2fa9aee00cddb459ea01c7',
    messagingSenderId: '262292692678',
    projectId: 'gestloc-135bb',
    authDomain: 'gestloc-135bb.firebaseapp.com',
    storageBucket: 'gestloc-135bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9FN71EsAmP93Fwu37ceqzwfW1o8vkwMQ',
    appId: '1:262292692678:android:ddc90c0263dcaa51ea01c7',
    messagingSenderId: '262292692678',
    projectId: 'gestloc-135bb',
    storageBucket: 'gestloc-135bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCefrZFWXzOr7fB-rYRtRc6lVoW4SGMyLk',
    appId: '1:262292692678:ios:5aa9870fd1634786ea01c7',
    messagingSenderId: '262292692678',
    projectId: 'gestloc-135bb',
    storageBucket: 'gestloc-135bb.appspot.com',
    iosClientId: '262292692678-vr7eh0s9bfmoa90i51jh9qu7c4vq4q9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestLoc2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCefrZFWXzOr7fB-rYRtRc6lVoW4SGMyLk',
    appId: '1:262292692678:ios:5aa9870fd1634786ea01c7',
    messagingSenderId: '262292692678',
    projectId: 'gestloc-135bb',
    storageBucket: 'gestloc-135bb.appspot.com',
    iosClientId: '262292692678-vr7eh0s9bfmoa90i51jh9qu7c4vq4q9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestLoc2',
  );
}
